spring:
  profiles:
    active: local
    group:
      local:
        - common
      test:
        - common
---
spring:
  config:
    activate:
      on-profile: common

  data:
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    consumer:
      properties:
        spring.json.trusted.packages: "com.simpaylog.*"
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: simulator
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      transaction: topic-transaction
      tx:
        request: topic-transaction-request
        response: topic-transaction-response


---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      maximum-pool-size: 30
      max-lifetime: 30000
      connection-timeout: 3000 # 커넥션을 얻기 위한 최대 대기 시간
      validation-timeout: 3000 # 커넥션 유효성 검사를 위한 제한 시간
      minimum-idle: 5 # 최소 유휴 커넥션 수
    url: jdbc:postgresql://localhost:5432/finance-data
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        format_sql: true
    show-sql: false
    open-in-view: false

logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

elasticsearch:
  host: localhost
  port: 9200
  scheme: http

  sql:
    init:
      mode: always