services:
  fdg-database:
    container_name: fdg-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: simpaylog/fdg-database
    volumes:
      - ./database/conf:/etc/postgresql/postgresql.conf
#      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_DB=${SPRING_DATABASE}
    ports:
      - "5432:5432"
  redis:
    container_name: fdg-redis
    image: redis:7.2-alpine
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379